import { Product, Service, Supplier, User } from '../types';

// Mock Users - Different salon types with active accounts
export const mockUsers: User[] = [
  // Glam Stock Central - General Beauty Salon (Admin)
  {
    id: '1',
    email: 'admin@glamstock.com',
    password: 'admin123',
    name: 'Ana García',
    role: 'admin',
    isActive: true,
    salonId: 'salon-1',
    salonName: 'Glam Stock Central',
    lastLogin: new Date('2024-01-14'),
    createdAt: new Date('2024-01-01'),
  },
  // Glam Stock Central - Manager
  {
    id: '2',
    email: 'manager@glamstock.com',
    password: 'manager123',
    name: 'María López',
    role: 'manager',
    isActive: true,
    salonId: 'salon-1',
    salonName: 'Glam Stock Central',
    lastLogin: new Date('2024-01-13'),
    createdAt: new Date('2024-01-01'),
  },
  // Glam Stock Central - Employee
  {
    id: '3',
    email: 'employee@glamstock.com',
    password: 'employee123',
    name: 'Carmen Rodríguez',
    role: 'employee',
    isActive: true,
    salonId: 'salon-1',
    salonName: 'Glam Stock Central',
    lastLogin: new Date('2024-01-12'),
    createdAt: new Date('2024-01-01'),
  },
  
  // Estilo y Tijeras - Hair Salon (Admin)
  {
    id: '4',
    email: 'admin@estiloytijeras.com',
    password: 'admin123',
    name: 'Isabella Torres',
    role: 'admin',
    isActive: true,
    salonId: 'salon-2',
    salonName: 'Estilo y Tijeras',
    lastLogin: new Date('2024-01-14'),
    createdAt: new Date('2024-01-01'),
  },
  // Estilo y Tijeras - Manager
  {
    id: '5',
    email: 'manager@estiloytijeras.com',
    password: 'manager123',
    name: 'Sofía Hernández',
    role: 'manager',
    isActive: true,
    salonId: 'salon-2',
    salonName: 'Estilo y Tijeras',
    lastLogin: new Date('2024-01-13'),
    createdAt: new Date('2024-01-01'),
  },
  // Estilo y Tijeras - Employee
  {
    id: '6',
    email: 'employee@estiloytijeras.com',
    password: 'employee123',
    name: 'Valentina Morales',
    role: 'employee',
    isActive: true,
    salonId: 'salon-2',
    salonName: 'Estilo y Tijeras',
    lastLogin: new Date('2024-01-11'),
    createdAt: new Date('2024-01-01'),
  },
  
  // Uñas Perfectas - Nail Salon (Admin)
  {
    id: '7',
    email: 'admin@unasperfectas.com',
    password: 'admin123',
    name: 'Camila Jiménez',
    role: 'admin',
    isActive: true,
    salonId: 'salon-3',
    salonName: 'Uñas Perfectas',
    lastLogin: new Date('2024-01-14'),
    createdAt: new Date('2024-01-01'),
  },
  // Uñas Perfectas - Manager
  {
    id: '8',
    email: 'manager@unasperfectas.com',
    password: 'manager123',
    name: 'Lucía Vargas',
    role: 'manager',
    isActive: true,
    salonId: 'salon-3',
    salonName: 'Uñas Perfectas',
    lastLogin: new Date('2024-01-13'),
    createdAt: new Date('2024-01-01'),
  },
  // Uñas Perfectas - Employee
  {
    id: '9',
    email: 'employee@unasperfectas.com',
    password: 'employee123',
    name: 'Daniela Castro',
    role: 'employee',
    isActive: true,
    salonId: 'salon-3',
    salonName: 'Uñas Perfectas',
    lastLogin: new Date('2024-01-10'),
    createdAt: new Date('2024-01-01'),
  },
  
  // Inactive account example
  {
    id: '10',
    email: 'inactive@example.com',
    password: 'inactive123',
    name: 'Usuario Inactivo',
    role: 'employee',
    isActive: false,
    salonId: 'salon-1',
    salonName: 'Glam Stock Central',
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Products - Distributed across different salons
export const mockProducts: Product[] = [
  // Glam Stock Central - General salon products
  {
    id: '1',
    name: 'Shampoo Premium Hidratante',
    brand: 'L\'Oréal Professional',
    category: 'Cuidado Capilar',
    stock: 45,
    minStock: 10,
    unit: 'ml',
    unitPrice: 28.99,
    expirationDate: new Date('2025-06-15'),
    supplierId: 'supplier-1',
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Acondicionador Reparador',
    brand: 'Schwarzkopf',
    category: 'Cuidado Capilar',
    stock: 32,
    minStock: 8,
    unit: 'ml',
    unitPrice: 24.50,
    expirationDate: new Date('2025-08-20'),
    supplierId: 'supplier-1',
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Base de Maquillaje HD',
    brand: 'MAC',
    category: 'Maquillaje',
    stock: 18,
    minStock: 5,
    unit: 'ml',
    unitPrice: 45.00,
    expirationDate: new Date('2025-12-31'),
    supplierId: 'supplier-2',
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Esmalte Gel Rojo Pasión',
    brand: 'OPI',
    category: 'Manicura',
    stock: 25,
    minStock: 6,
    unit: 'ml',
    unitPrice: 16.99,
    expirationDate: new Date('2026-03-15'),
    supplierId: 'supplier-3',
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Estilo y Tijeras - Hair salon focused products
  {
    id: '5',
    name: 'Tinte Castaño Chocolate',
    brand: 'Wella',
    category: 'Coloración',
    stock: 22,
    minStock: 5,
    unit: 'tubo',
    unitPrice: 35.50,
    expirationDate: new Date('2025-09-30'),
    supplierId: 'supplier-4',
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Oxidante 30 Vol',
    brand: 'Wella',
    category: 'Coloración',
    stock: 15,
    minStock: 4,
    unit: 'ml',
    unitPrice: 12.75,
    expirationDate: new Date('2025-07-15'),
    supplierId: 'supplier-4',
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: 'Mascarilla Keratina',
    brand: 'Matrix',
    category: 'Tratamientos',
    stock: 28,
    minStock: 7,
    unit: 'ml',
    unitPrice: 42.00,
    expirationDate: new Date('2025-11-20'),
    supplierId: 'supplier-1',
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    name: 'Spray Protector Térmico',
    brand: 'Redken',
    category: 'Cuidado Capilar',
    stock: 35,
    minStock: 8,
    unit: 'ml',
    unitPrice: 22.99,
    expirationDate: new Date('2025-10-10'),
    supplierId: 'supplier-1',
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Uñas Perfectas - Nail salon focused products
  {
    id: '9',
    name: 'Esmalte Gel Rosa Nude',
    brand: 'Essie',
    category: 'Manicura',
    stock: 30,
    minStock: 8,
    unit: 'ml',
    unitPrice: 14.99,
    expirationDate: new Date('2026-05-30'),
    supplierId: 'supplier-3',
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    name: 'Base Coat Fortalecedora',
    brand: 'Sally Hansen',
    category: 'Manicura',
    stock: 20,
    minStock: 5,
    unit: 'ml',
    unitPrice: 12.50,
    expirationDate: new Date('2026-02-28'),
    supplierId: 'supplier-3',
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '11',
    name: 'Top Coat Brillo Extremo',
    brand: 'China Glaze',
    category: 'Manicura',
    stock: 25,
    minStock: 6,
    unit: 'ml',
    unitPrice: 13.75,
    expirationDate: new Date('2026-04-15'),
    supplierId: 'supplier-3',
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    name: 'Aceite Cutículas Vitamina E',
    brand: 'CND',
    category: 'Cuidado de Uñas',
    stock: 18,
    minStock: 4,
    unit: 'ml',
    unitPrice: 18.99,
    expirationDate: new Date('2025-12-31'),
    supplierId: 'supplier-3',
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock Services - Distributed across different salons
export const mockServices: Service[] = [
  // Glam Stock Central - General salon services
  {
    id: '1',
    name: 'Corte y Peinado Completo',
    description: 'Corte personalizado con lavado, peinado y acabado profesional',
    price: 65.00,
    duration: 90,
    category: 'Cabello',
    products: [
      { productId: '1', quantity: 15, cost: 2.50 },
      { productId: '2', quantity: 10, cost: 1.80 }
    ],
    laborRate: 35.00,
    isActive: true,
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Maquillaje Profesional',
    description: 'Maquillaje completo para eventos especiales',
    price: 85.00,
    duration: 75,
    category: 'Maquillaje',
    products: [
      { productId: '3', quantity: 2, cost: 5.00 }
    ],
    laborRate: 45.00,
    isActive: true,
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Manicura Clásica',
    description: 'Manicura tradicional con esmaltado',
    price: 35.00,
    duration: 45,
    category: 'Uñas',
    products: [
      { productId: '4', quantity: 1, cost: 0.85 }
    ],
    laborRate: 25.00,
    isActive: true,
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Estilo y Tijeras - Hair salon services
  {
    id: '4',
    name: 'Coloración Completa',
    description: 'Aplicación de tinte con tratamiento post-color',
    price: 120.00,
    duration: 180,
    category: 'Coloración',
    products: [
      { productId: '5', quantity: 1, cost: 35.50 },
      { productId: '6', quantity: 50, cost: 6.38 }
    ],
    laborRate: 40.00,
    isActive: true,
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Tratamiento de Keratina',
    description: 'Tratamiento alisador y nutritivo con keratina',
    price: 180.00,
    duration: 240,
    category: 'Tratamientos',
    products: [
      { productId: '7', quantity: 30, cost: 12.60 },
      { productId: '8', quantity: 5, cost: 1.15 }
    ],
    laborRate: 45.00,
    isActive: true,
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Corte Masculino',
    description: 'Corte de cabello para hombre con acabado',
    price: 25.00,
    duration: 30,
    category: 'Cabello',
    products: [
      { productId: '1', quantity: 10, cost: 1.67 }
    ],
    laborRate: 30.00,
    isActive: true,
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Uñas Perfectas - Nail salon services
  {
    id: '7',
    name: 'Manicura Gel Completa',
    description: 'Manicura con esmaltado en gel y diseño básico',
    price: 45.00,
    duration: 60,
    category: 'Manicura',
    products: [
      { productId: '10', quantity: 1, cost: 0.63 },
      { productId: '9', quantity: 1, cost: 0.75 },
      { productId: '11', quantity: 1, cost: 0.69 }
    ],
    laborRate: 30.00,
    isActive: true,
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    name: 'Pedicura Spa',
    description: 'Pedicura relajante con exfoliación y masaje',
    price: 55.00,
    duration: 75,
    category: 'Pedicura',
    products: [
      { productId: '12', quantity: 2, cost: 1.90 },
      { productId: '9', quantity: 1, cost: 0.75 }
    ],
    laborRate: 28.00,
    isActive: true,
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    name: 'Diseño de Uñas Artístico',
    description: 'Diseño personalizado con técnicas avanzadas',
    price: 75.00,
    duration: 90,
    category: 'Arte en Uñas',
    products: [
      { productId: '10', quantity: 1, cost: 0.63 },
      { productId: '9', quantity: 2, cost: 1.50 },
      { productId: '11', quantity: 1, cost: 0.69 }
    ],
    laborRate: 35.00,
    isActive: true,
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock Suppliers - Distributed across different salons
export const mockSuppliers: Supplier[] = [
  // General beauty supplier
  {
    id: 'supplier-1',
    name: 'Beauty Supply Professional',
    contactPerson: 'María González',
    email: 'maria@beautysupply.com',
    phone: '+34 912 345 678',
    address: 'Calle Mayor 123, Madrid, España',
    products: ['1', '2', '7', '8'],
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'supplier-2',
    name: 'Cosmetics & Makeup Pro',
    contactPerson: 'Carlos Rodríguez',
    email: 'carlos@cosmeticspro.com',
    phone: '+34 913 456 789',
    address: 'Avenida de la Belleza 456, Madrid, España',
    products: ['3'],
    salonId: 'salon-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  
  // Nail products supplier
  {
    id: 'supplier-3',
    name: 'Nail Art Distributors',
    contactPerson: 'Ana Martínez',
    email: 'ana@nailart.com',
    phone: '+34 914 567 890',
    address: 'Plaza de las Uñas 789, Madrid, España',
    products: ['4', '9', '10', '11', '12'],
    salonId: 'salon-3',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  
  // Hair color specialist supplier
  {
    id: 'supplier-4',
    name: 'Color Hair Specialists',
    contactPerson: 'Laura Jiménez',
    email: 'laura@colorhair.com',
    phone: '+34 915 678 901',
    address: 'Calle del Color 321, Madrid, España',
    products: ['5', '6'],
    salonId: 'salon-2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];