import { Product, Service, Supplier, User } from '../types';
import { addDays, subDays } from 'date-fns';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Shampoo Hidratante',
    brand: 'L\'Oréal',
    category: 'Cuidado Capilar',
    stock: 15,
    minStock: 20,
    unit: 'ml',
    unitPrice: 25.50,
    expirationDate: addDays(new Date(), 45),
    supplierId: '1',
    createdAt: subDays(new Date(), 30),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Tinte Profesional',
    brand: 'Schwarzkopf',
    category: 'Coloración',
    stock: 8,
    minStock: 10,
    unit: 'tubo',
    unitPrice: 18.75,
    expirationDate: addDays(new Date(), 90),
    supplierId: '1',
    createdAt: subDays(new Date(), 25),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Mascarilla Nutritiva',
    brand: 'Kerastase',
    category: 'Tratamientos',
    stock: 12,
    minStock: 8,
    unit: 'ml',
    unitPrice: 45.00,
    expirationDate: addDays(new Date(), 120),
    supplierId: '2',
    createdAt: subDays(new Date(), 20),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Esmalte de Uñas',
    brand: 'OPI',
    category: 'Manicura',
    stock: 25,
    minStock: 15,
    unit: 'ml',
    unitPrice: 12.99,
    expirationDate: addDays(new Date(), 180),
    supplierId: '3',
    createdAt: subDays(new Date(), 15),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Crema Facial Anti-edad',
    brand: 'Vichy',
    category: 'Cuidado Facial',
    stock: 6,
    minStock: 10,
    unit: 'ml',
    unitPrice: 55.00,
    expirationDate: addDays(new Date(), 15),
    supplierId: '2',
    createdAt: subDays(new Date(), 10),
    updatedAt: new Date(),
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'Corte y Peinado',
    description: 'Corte personalizado con peinado profesional',
    price: 35.00,
    duration: 60,
    category: 'Cabello',
    products: [
      { productId: '1', quantity: 50, cost: 1.27 },
    ],
    isActive: true,
    createdAt: subDays(new Date(), 60),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Coloración Completa',
    description: 'Aplicación de tinte con tratamiento post-color',
    price: 80.00,
    duration: 120,
    category: 'Cabello',
    products: [
      { productId: '2', quantity: 1, cost: 18.75 },
      { productId: '3', quantity: 30, cost: 1.35 },
    ],
    isActive: true,
    createdAt: subDays(new Date(), 55),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Manicura Completa',
    description: 'Manicura con esmaltado profesional',
    price: 25.00,
    duration: 45,
    category: 'Uñas',
    products: [
      { productId: '4', quantity: 2, cost: 0.26 },
    ],
    isActive: true,
    createdAt: subDays(new Date(), 50),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Tratamiento Facial',
    description: 'Limpieza facial profunda con mascarilla',
    price: 65.00,
    duration: 90,
    category: 'Facial',
    products: [
      { productId: '5', quantity: 5, cost: 2.75 },
    ],
    isActive: true,
    createdAt: subDays(new Date(), 45),
    updatedAt: new Date(),
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Distribuidora Beauty Pro',
    contactPerson: 'María González',
    email: 'maria@beautypro.com',
    phone: '+34 912 345 678',
    address: 'Calle Mayor 123, Madrid',
    products: ['1', '2'],
    createdAt: subDays(new Date(), 90),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Cosmética Premium S.L.',
    contactPerson: 'Carlos Ruiz',
    email: 'carlos@cosmeticapremium.es',
    phone: '+34 987 654 321',
    address: 'Avenida Belleza 456, Barcelona',
    products: ['3', '5'],
    createdAt: subDays(new Date(), 85),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Nail Art Supplies',
    contactPerson: 'Ana López',
    email: 'ana@nailart.com',
    phone: '+34 654 321 987',
    address: 'Plaza Uñas 789, Valencia',
    products: ['4'],
    createdAt: subDays(new Date(), 80),
    updatedAt: new Date(),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@beautysalon.com',
    password: 'admin123',
    name: 'María Administradora',
    role: 'admin',
    isActive: true,
    lastLogin: subDays(new Date(), 1),
    createdAt: subDays(new Date(), 365),
  },
  {
    id: '2',
    email: 'manager@beautysalon.com',
    password: 'manager123',
    name: 'Carlos Gerente',
    role: 'manager',
    isActive: true,
    lastLogin: subDays(new Date(), 2),
    createdAt: subDays(new Date(), 200),
  },
  {
    id: '3',
    email: 'employee1@beautysalon.com',
    password: 'emp123',
    name: 'Ana Estilista',
    role: 'employee',
    isActive: true,
    lastLogin: subDays(new Date(), 3),
    createdAt: subDays(new Date(), 150),
  },
  {
    id: '4',
    email: 'employee2@beautysalon.com',
    password: 'emp456',
    name: 'Laura Manicurista',
    role: 'employee',
    isActive: true,
    lastLogin: subDays(new Date(), 5),
    createdAt: subDays(new Date(), 100),
  },
  {
    id: '5',
    email: 'employee3@beautysalon.com',
    password: 'emp789',
    name: 'Sofia Esteticista',
    role: 'employee',
    isActive: false,
    lastLogin: subDays(new Date(), 30),
    createdAt: subDays(new Date(), 80),
  },
];